server:
  port: 8081
  servlet:
    context-path: /accountApi

logging:
  level:
    org:
      springframework:
        web: INFO
      hibernate: ERROR

spring:
  application:
    name: account-microservice
  cloud:
    loadbalancer:
      ribbon:
        enabled: false  # Si no quieres usar Ribbon
    gateway:
      routes:
        - id: customer-microservice
          uri: http://localhost:8080
          predicates:
            - Path=/customerApi/**
        - id: account-microservice
          uri: http://localhost:8081
          predicates:
            - Path=/accountApi/**
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL;INIT=RUNSCRIPT FROM 'classpath:BaseDatos.sql'
    driverClassName: org.h2.Driver
    username: sa
    password: password
    platform: h2
    initialize: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  jackson:
    serialization:
      fail-on-empty-beans: false

feign:
  hystrix:
    enabled: true